//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CGWork.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CGWorkTYPE                  129
#define IDD_PERSPECTIVE_DLG             145
#define IDD_MOUS_SENS                   147
#define IDD_COLORS                      149
#define IDD_LIGHTING_DLG                155
#define IDD_SCREENSHOT                  156
#define IDD_ANIMATION_SPEED             158
#define IDD_FOG                         160
#define IDD_BLUR_DLG                    163
#define IDC_LIGHT_SPACE                 1010
#define IDC_RADIO_LIGHT1                1017
#define IDC_RADIO_LIGHT2                1018
#define IDC_RADIO_LIGHT3                1019
#define IDC_RADIO_LIGHT4                1020
#define IDC_RADIO_LIGHT5                1021
#define IDC_RADIO_LIGHT6                1022
#define IDC_RADIO_LIGHT7                1023
#define IDC_RADIO_LIGHT8                1024
#define IDC_AMBL_COLOR_R                1025
#define IDC_LIGHT_ENABLED               1026
#define IDC_AMBL_COLOR_G                1027
#define IDC_AMBL_COLOR_B                1028
#define IDC_LIGHT_COLOR_R               1029
#define IDC_LIGHT_COLOR_G               1030
#define IDC_LIGHT_COLOR_B               1031
#define IDC_LIGHT_POS_X                 1032
#define IDC_LIGHT_POS_Y                 1033
#define IDC_LIGHT_POS_Z                 1034
#define IDC_LIGHT_DIR_X                 1035
#define IDC_LIGHT_DIR_Y                 1036
#define IDC_LIGHT_DIR_Z                 1037
#define IDC_LIGHT_TYPE                  1038
#define IDC_EDIT1                       1041
#define IDC_DEPTH_CONTROL               1041
#define IDC_EDIT_MOUSE_SENS             1041
#define IDC_BWWRFRMCLR                  1042
#define IDC_EDITHSCRN                   1042
#define IDC_BNRMLSCLR                   1043
#define IDC_BBCKGRNDCLR                 1044
#define IDC_WIREFRAME_COLOR             1045
#define IDC_NORMAL_COLOR                1046
#define IDC_BG_COLOR                    1047
#define IDC_BBOX_COLOR                  1048
#define IDC_SILOUHETTE_COLOR            1049
#define IDC_LIGHT_DIFFUSE               1051
#define IDC_LIGHT_SPECULAR              1052
#define IDC_LIGHT_COLOR                 1053
#define IDC_AMBIANT_COLOR               1054
#define IDC_AMBIANT_INTENSITY           1055
#define IDC_AMBIANT_EXPONENT            1056
#define IDC_LIGHT_N                     1060
#define IDC_EDITWSCRN                   1060
#define IDC_FOG_ENABLED                 1061
#define IDC_FOG_COLOR                   1062
#define IDC_FOG_FAR                     1063
#define IDC_FOG_INTENSITY               1064
#define IDC_FOG_NEAR                    1065
#define IDC_BLUR_ENABLE                 1066
#define IDC_BLUR_FACTOR                 1067
#define ID_FILE_LOAD                    32771
#define ID_VIEW_ORTHOGRAPHIC            32772
#define ID_VIEW_PERSPECTIVE             32773
#define ID_ACTION_ROTATE                32774
#define ID_ACTION_TRANSLATE             32775
#define ID_ACTION_SCALE                 32776
#define ID_AXIS_X                       32777
#define ID_AXIS_Y                       32778
#define ID_AXIS_Z                       32779
#define ID_LIGHT_SHADING_FLAT           32781
#define ID_LIGHT_SHADING_GOURAUD        32782
#define ID_LIGHT_CONSTANTS              32783
#define ID_ANIM_PLAY                    32793
#define ID_ANIM_CLEAR                   32794
#define ID_ANIM_SNAPSHOT                32795
#define ID_BUTTON_SUBDIVIDE             32797
#define ID_OPTIONS_PERSPECTIVECONTROL   32798
#define ID_OPTIONS_MOUSESENSITIVITY     32799
#define ID_BUTTON32802                  32802
#define ID_NORMAL_VERTICE_TOGGLE        32802
#define ID_NORMAL_PLANE_TOGGLE          32803
#define ID_OPTIONS_NORMALSSOURCE        32804
#define ID_NORMALSSOURCE_POLYGON        32805
#define ID_NORMALSSOURCE_VERTEX         32806
#define ID_POLYGON_INCLUDED             32807
#define ID_POLYGON_CALCULATED           32808
#define ID_VERTEX_INCLUDED              32809
#define ID_VERTEX_CALCULATED            32810
#define ID_OBJECT_TRANSFORM             32811
#define ID_VIEW_TRANSFORM               32812
#define ID_POLYGON_CALCULATED32813      32813
#define ID_POLYGON_NONE                 32814
#define ID_VERTEX_NONE                  32815
#define ID_VERTEX_CALCULATED32816       32816
#define ID_ACTION_TRANSFORMOBJECT       32817
#define ID_ACTION_TRANSFORMVIEW         32818
#define ID_SHOW_BBOX                    32819
#define ID_OPTIONS_COLORS               32820
#define IDD_FINENESS                    32821
#define IDD_DIAFINENESS                 32821
#define ID_MFINENESS                    32822
#define ID_RENDER_FLAT                  32825
#define ID_RENDER_GOURAUD               32826
#define ID_BUTTON32827                  32827
#define ID_RENDER_PHONG                 32827
#define ID_RENDER_SQUELETON             32828
#define ID_SHADING_PHONG                32829
#define ID_RENDER_SQUELETON32830        32830
#define ID_RENDER_ONSCREEN              32831
#define ID_RENDER_TOFILE                32832
#define ID_BACKFACE_CULLING             32833
#define ID_Z_BUFFER                     32834
#define ID_POLYGON_INVERTED             32835
#define ID_VERTEX_INVERTED              32836
#define ID_FILE_LOADBACKGROUND          32837
#define ID_BG_REPEAT                    32839
#define ID_BG_STRETCH                   32840
#define ID_SILOUHETTE                   32841
#define ID_ANTI_NOAA                    32842
#define ID_ANTI_SSAAX3                  32843
#define ID_ANTI_SSAAX5                  32844
#define ID_ANTI_BOXFILTER               32845
#define ID_ANTI_TRIANGLEFILTER          32846
#define ID_ANTI_GAUSSIANFILTER          32847
#define ID_ANTI_SINCFILTER              32848
#define ID_RECORD                       32849
#define ID_PLAY                         32850
#define ID_STOP                         32852
#define ID_ANIMATION_SPEED              32853
#define ID_ANIMATION_SAVEANIMATION      32854
#define ID_OPTIONS_FOG                  32855
#define ID_OPTIONS_MOTIONBLUR           32856
#define ID_BUTTON32857                  32857
#define ID_CLEAR_VIEW                   32857

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32858
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
